#!/usr/bin/env node
/**
 * Vendors the webfonts named in brand/tokens.json into brand/fonts/.
 *
 * Renders must be byte-reproducible across machines and CI. Relying on whatever
 * fonts happen to be installed on the box is how a poster silently ships in
 * DejaVu Sans. This downloads the real files and inlines them as base64 in
 * brand/fonts/fonts.css, which render.mjs embeds into every artboard.
 *
 * Re-run after changing any type token:  npm run fonts
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const tokens = JSON.parse(readFileSync(resolve(root, "brand/tokens.json"), "utf8"));

const GENERIC = new Set(["serif", "sans-serif", "monospace", "system-ui", "cursive"]);

// Derive the font list from the tokens themselves, so type and fonts never drift.
const wanted = [];
for (const [key, def] of Object.entries(tokens.type)) {
  if (key === "scale" || !def.family) continue;
  const first = def.family.split(",")[0].trim().replace(/^["']|["']$/g, "");
  if (GENERIC.has(first) || first.startsWith("-")) continue;
  wanted.push({ key, family: first, weights: def.weights ?? [400, 700] });
}

const UA = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36";

async function fetchFamily({ family, weights }) {
  const url = `https://fonts.googleapis.com/css2?family=${encodeURIComponent(family)}:wght@${weights.join(";")}&display=swap`;
  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`${family}: HTTP ${res.status} — check the family name is on Google Fonts, or vendor it manually into brand/fonts/.`);
  return res.text();
}

async function inlineUrls(css) {
  const urls = [...css.matchAll(/url\((https:\/\/[^)]+\.woff2)\)/g)].map((m) => m[1]);
  const uniq = [...new Set(urls)];
  let bytes = 0;
  for (const u of uniq) {
    const r = await fetch(u, { headers: { "User-Agent": UA } });
    if (!r.ok) continue;
    const buf = Buffer.from(await r.arrayBuffer());
    bytes += buf.length;
    css = css.replaceAll(`url(${u})`, `url(data:font/woff2;base64,${buf.toString("base64")})`);
  }
  return { css, bytes, count: uniq.length };
}

const parts = ["/* GENERATED by scripts/fetch-fonts.mjs — DO NOT EDIT, DO NOT COMMIT. Run `npm run fonts`. */"];
let totalBytes = 0, totalFiles = 0;

for (const f of wanted) {
  process.stdout.write(`  ${f.family} (${f.weights.join(", ")}) … `);
  try {
    const raw = await fetchFamily(f);
    const { css, bytes, count } = await inlineUrls(raw);
    parts.push(`\n/* — ${f.family} — */\n${css}`);
    totalBytes += bytes; totalFiles += count;
    console.log(`${count} files, ${(bytes / 1024).toFixed(0)} KB`);
  } catch (e) {
    console.log(`FAILED — ${e.message}`);
  }
}

mkdirSync(resolve(root, "brand/fonts"), { recursive: true });
writeFileSync(resolve(root, "brand/fonts/fonts.css"), parts.join("\n"));
console.log(`\n✓ brand/fonts/fonts.css — ${totalFiles} files, ${(totalBytes / 1024 / 1024).toFixed(2)} MB inlined`);
