#!/usr/bin/env node
/**
 * brand/tokens.json  ->  src/css/tokens.generated.css
 *
 * The single bridge between the brand definition and everything that renders.
 * Emits a Tailwind v4 @theme block, so every token is usable BOTH as a utility
 * class (bg-primary, font-display, text-3xl) and as a raw CSS var
 * (var(--color-primary)) inside hand-written CSS and SVG.
 *
 * Never hand-edit the output. Edit brand/tokens.json and re-run.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const tokens = JSON.parse(readFileSync(resolve(root, "brand/tokens.json"), "utf8"));

const lines = [];
const push = (s = "") => lines.push(s);

push("/* GENERATED by scripts/tokens-to-css.mjs — DO NOT EDIT.");
push(`   Source: brand/tokens.json (v${tokens.$meta.version}, status: ${tokens.$meta.status})`);
push("   Edit the JSON and run `npm run tokens`. */");
push();
push("@theme {");

push("  /* — color — */");
for (const [name, def] of Object.entries(tokens.color)) {
  push(`  --color-${name}: ${def.value};${def.use ? ` /* ${def.use} */` : ""}`);
}

push();
push("  /* — type families — */");
for (const [name, def] of Object.entries(tokens.type)) {
  if (name === "scale") continue;
  push(`  --font-${name}: ${def.family};`);
}

push();
push("  /* — type scale — */");
for (const [name, value] of Object.entries(tokens.type.scale)) {
  push(`  --text-${name}: ${value};`);
}

push();
push("  /* — spacing — */");
for (const [name, value] of Object.entries(tokens.space.scale)) {
  push(`  --spacing-${name}: ${value};`);
}

push();
push("  /* — radius — */");
for (const [name, value] of Object.entries(tokens.radius)) {
  push(`  --radius-${name}: ${value};`);
}

push("}");
push();
push("/* — script-specific defaults; applied by [lang] so templates just tag the span — */");
push(":lang(bn), [lang=\"bn\"] {");
push(`  font-family: var(--font-bengali);`);
push(`  line-height: ${tokens.type.bengali.lineHeightBoost};`);
push("}");
push("[lang=\"ar\"] {");
push(`  font-family: var(--font-arabic);`);
push(`  line-height: ${tokens.type.arabic.lineHeightBoost};`);
push("  direction: rtl;");
push("}");
push();
push("/* — motif defaults, consumed by the pattern macro — */");
push(":root {");
push(`  --motif-stroke: ${tokens.motif.strokeWidth};`);
push(`  --motif-opacity-dark: ${tokens.motif.opacityOnDark};`);
push(`  --motif-opacity-light: ${tokens.motif.opacityOnLight};`);
push("}");
push();

const out = resolve(root, "src/css/tokens.generated.css");
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, lines.join("\n"));

const n = Object.keys(tokens.color).length + Object.keys(tokens.type.scale).length;
console.log(`✓ tokens → src/css/tokens.generated.css (${n} values, brand v${tokens.$meta.version})`);
if (tokens.$meta.status === "PLACEHOLDER") {
  console.log("  ⚠ brand status is PLACEHOLDER — values are provisional until reference extraction runs.");
}
